# Generated by Django 5.1.1 on 2024-09-16 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('effects', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='effects',
            field=models.TextField(default='No effects'),
        ),
    ]
