# Generated by Django 5.1.1 on 2024-09-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productentry_product_effects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductEntry',
        ),
    ]
